language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --no-interaction
  - iconv -V

script:
  - vendor/bin/phpunit

